import { defineConfig, type Plugin } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

/**
 * Provides a hermetic, in-memory stand-in for the "content-collections" virtual module.
 *
 * The real module is generated by @content-collections/next's webpack plugin during
 * `next build`/`next dev` and lives at `.content-collections/generated`, which is
 * gitignored and does not exist on a clean checkout before a build has run. Vitest
 * has no equivalent codegen step, so any test file that transitively imports from
 * "content-collections" (e.g. via config/navigation.ts) needs a resolvable stand-in
 * that does not depend on that build artifact ever having been produced. Tests that
 * care about real collection data should use `vi.mock('content-collections', ...)`
 * to override this stub with their own fixture.
 */
function stubContentCollectionsPlugin(): Plugin {
    const virtualId = 'content-collections';
    const resolvedVirtualId = '\0' + virtualId;
    return {
        name: 'stub-content-collections',
        resolveId(id) {
            if (id === virtualId) {
                return resolvedVirtualId;
            }
            return null;
        },
        load(id) {
            if (id === resolvedVirtualId) {
                return 'export const allBlogs = []; export const allInstruments = [];';
            }
            return null;
        },
    };
}

export default defineConfig({
    plugins: [react(), stubContentCollectionsPlugin()],
    test: {
        environment: 'jsdom',
        globals: true,
        setupFiles: [],
        include: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}'],
        exclude: ['**/node_modules/**', 'tests/integration/**', '.worktrees/**', '.claude/**'],
        alias: {
            '@': path.resolve(__dirname, './'),
        },
        // Use forks pool to avoid jsdom/webidl-conversions compatibility issues in CI environments
        // This isolates each test file in its own process, preventing module loading conflicts
        pool: 'forks',
    },
});
