import type { RelayModel } from '@/types/relay-model';

export const relayModels: RelayModel[] = [
    {
        modelKey: 'lipstick',
        name: 'Relay Lipstick',
        tagline: 'Signature · Articulate · Lipstick layer',
        genres: 'Blues · Rock · Alternative · Indie',
        description: 'The reference model and first release: expressive dual humbuckers with a middle lipstick as a curated alternate voice — familiar core behavior plus a second identity of the same instrument, not a novelty.',
        status: 'lab',
        href: '/relay/lipstick',
    },
    {
        modelKey: 'reef',
        name: 'Relay Reef',
        tagline: 'Danelectro soul · Humbucker punch · Lipstick shimmer',
        genres: 'Indie · Surf · Alt Country · Shoegaze · Studio',
        description: 'Bridge humbucker for warmth and sustain; middle and neck lipsticks wired as a single network for glassy, piano-like articulation. Two distinct voices, one concentric tone pot to shape each independently.',
        status: 'lab',
        href: '/relay/reef',
    },
    {
        modelKey: 'velvet',
        name: 'Relay Velvet',
        tagline: 'Warm authority · Club presence',
        genres: 'Jazz · Blues · Soul · R&B',
        description: 'The warm, fat, classy club model — a distinct center of gravity. The middle pickup is a true core voice (5-way family), poised and present so the band can orbit the guitar.',
        status: 'lab',
        href: '/relay/velvet',
    },
    {
        modelKey: 'arc',
        name: 'Relay Arc',
        tagline: 'Chime · Air · Spatial clarity',
        genres: 'Clean pop · Indie · Ambient · Country',
        description: 'The airy, spatial, chime-forward model: width, shimmer, and clarity without thinning out — open, ringing, and alive rather than club-warm or mid-forward.',
        status: 'lab',
        href: '/relay/arc',
    },
    {
        modelKey: 'torch',
        name: 'Relay Torch',
        tagline: 'Vocal mids · Hooky · Contemporary',
        genres: 'Rock · Pop · Alternative · Modern country',
        description: 'The rude, vocal-mid, modern-radio voice: attitude and edge with a P90-type middle as a core position (5-way family) — emotionally direct and hooky without becoming a metal guitar.',
        status: 'lab',
        href: '/relay/torch',
    },
    {
        modelKey: 'current',
        name: 'Relay Current',
        tagline: 'Punch · Cut · Fast attack',
        genres: 'Funk · Pop · Rock',
        description: "Punchy, cutting, and immediate: strong projection and edge definition (3-way family with the middle as a fast alternate layer). The line's sharpest non-metal tool — less warm than Velvet, less spacious than Arc, less throaty than Torch.",
        status: 'lab',
        href: '/relay/current',
    },
    {
        modelKey: 'hammer',
        name: 'Relay Hammer',
        tagline: 'High gain · Tight · Uncompromising',
        genres: 'Metal · Hard rock',
        description: 'The dedicated heavy model: high-gain authority, tight aggressive attack, and rail-style passive pickups — the specialty brute of the line, direct and forceful rather than elegant.',
        status: 'lab',
        href: '/relay/hammer',
    },
];
