import type { RelayVoicing } from '@/types/relay-voicing';

export const relayVoicings: RelayVoicing[] = [
    {
        slug: 'lipstick',
        name: 'Relay Lipstick',
        tagline: 'Humbuckers · Lipstick shaper',
        genres: 'Blues · Rock · Alternative · Indie',
        description: 'The reference Relay model: bridge and neck humbuckers provide the main voices, while the middle lipstick reshapes them with contour, texture, and air.',
        status: 'ready',
        interaction: {
            category: 'Shaper',
            summary: 'The middle lipstick reshapes the selected humbucker voice instead of acting as a standalone pickup sound.',
        },
        pickupMap: {
            bridge: { type: 'humbucker', magnet: 'Alnico V', resistance: '11.2K' },
            middle: { type: 'lipstick', magnet: 'Alnico II', resistance: '6.0K', role: 'shaper' },
            neck: { type: 'humbucker', magnet: 'Alnico II', resistance: '7.6K' },
            selector: '3-way',
            volume: 'push-push',
            tone: 'push-pull',
        },
        href: '/relay/voicings/lipstick',
    },
    {
        slug: 'reef',
        name: 'Relay Reef',
        tagline: 'Humbucker · Dual-lipstick subsystem',
        genres: 'Indie · Surf · Alt Country · Shoegaze · Studio',
        description: 'Two voice families in one body: a bridge humbucker and an independently controlled dual-lipstick subsystem for high-contrast clean and driven sounds.',
        status: 'lab',
        interaction: {
            category: 'Subsystem',
            summary: 'The middle and neck lipsticks form an independently controlled subsystem alongside the bridge humbucker.',
        },
        pickupMap: {
            bridge: { type: 'humbucker' },
            middle: { type: 'lipstick', role: 'subsystem' },
            neck: { type: 'lipstick', role: 'subsystem' },
            selector: '5-way',
            volume: 'concentric',
            tone: 'concentric',
        },
        href: '/relay/voicings/reef',
    },
    {
        slug: 'velvet',
        name: 'Relay Velvet',
        tagline: 'Jazz-club center · Controlled warmth',
        genres: 'Jazz · Blues · Soul · R&B',
        description: 'A middle-primary model for players who put the guitar at the center of a small room: rounded attack, controlled mids, and enough presence to carry the act clean.',
        status: 'ready',
        interaction: {
            category: 'Primary voice',
            summary: 'The middle pickup is a main selector destination for exposed clean and low-gain performance.',
        },
        pickupMap: {
            bridge: { type: 'humbucker', magnet: 'Alnico II', resistance: '8.6K' },
            middle: { type: 'filtertron', magnet: 'Ceramic', resistance: '8.0K', role: 'primary' },
            neck: { type: 'humbucker', magnet: 'Alnico II', resistance: '7.6K' },
            selector: '5-way',
            volume: 'standard',
            tone: 'push-pull',
        },
        href: '/relay/voicings/velvet',
    },
    {
        slug: 'arc',
        name: 'Relay Arc',
        tagline: 'Open · Spatial · Separated',
        genres: 'Clean pop · Indie · Ambient · Country',
        description: 'A middle-primary model focused on clarity and separation: wide clean sounds that keep detail under reverb, delay, and other effects.',
        status: 'lab',
        interaction: {
            category: 'Primary voice',
            summary: 'The middle pickup is a main selector destination for open, spatial sounds with strong note separation.',
        },
        pickupMap: {
            bridge: { type: 'filtertron', magnet: 'Alnico V', resistance: '9.5K' },
            middle: { type: 'humbucker', magnet: 'Alnico V', resistance: '9.0K', role: 'primary' },
            neck: { type: 'humbucker', magnet: 'Alnico V', resistance: '8.0K' },
            selector: '5-way',
            volume: 'standard',
            tone: 'push-pull',
        },
        href: '/relay/voicings/arc',
    },
    {
        slug: 'torch',
        name: 'Relay Torch',
        tagline: 'Punch · Vocal mids · Presence',
        genres: 'Rock · Pop · Alternative · Modern country',
        description: 'A P90-type middle pickup acts as a primary voice, giving the guitar stronger mids, more punch, and a forward position in the mix.',
        status: 'ready',
        interaction: {
            category: 'Primary voice',
            summary: 'The P90-type middle pickup is a main selector destination for punch, vocal mids, and mix presence.',
        },
        pickupMap: {
            bridge: { type: 'humbucker', magnet: 'Alnico V', resistance: '11.2K' },
            middle: { type: 'p90', magnet: 'Alnico V', resistance: '8.7K', role: 'primary' },
            neck: { type: 'humbucker', magnet: 'Alnico II', resistance: '7.6K' },
            selector: '5-way',
            volume: 'standard',
            tone: 'push-pull',
        },
        href: '/relay/voicings/torch',
    },
    {
        slug: 'current',
        name: 'Relay Current',
        tagline: 'Fast attack · Upper-mid focus',
        genres: 'Funk · Pop · Rock',
        description: 'A rhythm-first humbucker model with a middle augment layer that tightens lows, sharpens attack, and improves mix placement without acting like a boost.',
        status: 'lab',
        interaction: {
            category: 'Augment layer',
            summary: 'The middle pickup is added after the humbucker selection to tighten lows and sharpen attack.',
        },
        pickupMap: {
            bridge: { type: 'humbucker', magnet: 'Alnico V', resistance: '9.4K' },
            middle: { type: 'filtertron', magnet: 'Ceramic', resistance: '~10K', role: 'augment' },
            neck: { type: 'humbucker', magnet: 'Alnico V', resistance: '8.0K' },
            selector: '3-way',
            volume: 'push-push',
            tone: 'push-pull',
        },
        href: '/relay/voicings/current',
    },
    {
        slug: 'hammer',
        name: 'Relay Hammer',
        tagline: 'High gain · Rails · Concept',
        genres: 'Metal · Hard rock',
        description: 'A high-gain concept using rail pickups, aimed at tight low end, saturation, and controlled aggression. Final switching behavior is still in development.',
        status: 'concept',
        interaction: {
            category: 'Concept',
            summary: 'The rail-pickup set points toward high-gain behavior, but the final switching interaction is not finalized.',
        },
        pickupMap: {
            bridge: { type: 'rail', magnet: 'Ceramic', resistance: '16.2K' },
            middle: { type: 'rail', magnet: 'Ceramic', resistance: '10.0K', role: 'concept' },
            neck: { type: 'rail', magnet: 'Ceramic', resistance: '10.4K' },
            selector: 'super-switch',
            volume: 'push-push',
            tone: 'push-pull',
        },
        href: '/relay/voicings/hammer',
    },
];
